version: "3.9"
services:
  route-service:
    build: .
    ports:
      - "5003:5003"
    environment:
      - PostgreSQLConnection=${PostgreSQLConnection}
      - SEND_GRID_API_KEY=${SEND_GRID_API_KEY}
      - PORT=${PORT}
